let LODDING = "LODDING",
  LODDING_END = "LODDING_END",
  ADD_ITEMS = "ADD_ITEMS",
  ADD_ITEM = "ADD_ITEM",
  DELEAT_ITEM = "DELEAT_ITEM",
  ERROR = "ERROR";
export { LODDING, LODDING_END, ADD_ITEMS, ADD_ITEM, DELEAT_ITEM, ERROR };
